{-# LANGUAGE GADTs #-}

module CubicalInterval where

--------------------------------------------------------------------------------
-- 1. The Interval Type (Symbolic representation)
--------------------------------------------------------------------------------

-- | The Interval I is generated by endpoints 0 and 1, 
-- connections (meet/join), and an involution (negation).
data I 
    = I0 
    | I1 
    | Meet I I 
    | Join I I 
    | Neg I
    deriving (Show, Eq)

-- | Simplifier (Normalization)
-- In a real Cubical system, these equalities are definitional.
-- Here, we manually simplify the lattice logic.
squeeze :: I -> I
squeeze I0 = I0
squeeze I1 = I1
squeeze (Neg I0) = I1
squeeze (Neg I1) = I0
squeeze (Neg (Neg i)) = squeeze i
squeeze (Meet i j) = 
    case (squeeze i, squeeze j) of
        (I0, _)  -> I0
        (_, I0)  -> I0
        (I1, x)  -> x
        (x, I1)  -> x
        (a, b)   | a == b -> a
                 | otherwise -> Meet a b
squeeze (Join i j) = 
    case (squeeze i, squeeze j) of
        (I1, _)  -> I1
        (_, I1)  -> I1
        (I0, x)  -> x
        (x, I0)  -> x
        (a, b)   | a == b -> a
                 | otherwise -> Join a b
squeeze x = x

--------------------------------------------------------------------------------
-- 2. Paths and Operations
--------------------------------------------------------------------------------

-- | A Path in space A is a function from the Interval to A.
type Path a = I -> a

-- | Reverses a path (p⁻¹)
rev :: Path a -> Path a
rev p i = p (squeeze (Neg i))

-- | Constant path (Reflexivity)
refl :: a -> Path a
refl x _ = x

-- | A Square is a function from two interval dimensions (I -> I -> A)
type Square a = I -> I -> a

--------------------------------------------------------------------------------
-- 3. Example: A Higher-Dimensional Cubical Surface
--------------------------------------------------------------------------------

-- | We can represent a 2D surface (a square) where the 
-- four edges are defined by the interval boundaries.
boundaryCheck :: Square String -> IO ()
boundaryCheck sq = do
    putStrLn $ "Left Edge  (0, i): " ++ sq I0 (Meet I1 I1)
    putStrLn $ "Right Edge (1, i): " ++ sq I1 (Meet I1 I1)
    putStrLn $ "Bottom Edge(i, 0): " ++ sq (Meet I1 I1) I0
    putStrLn $ "Top Edge   (i, 1): " ++ sq (Meet I1 I1) I1

-- | Creating a simple "Interpolated" string square
mySquare :: Square String
mySquare i j = "Point at (" ++ show (squeeze i) ++ ", " ++ show (squeeze j) ++ ")"

--------------------------------------------------------------------------------
-- 4. Main Execution
--------------------------------------------------------------------------------

main :: IO ()
main = do
    let i = Meet I1 (Neg I0) -- This is effectively 1 ∧ 1 = 1
    putStrLn $ "Simplified Meet I1 (Neg I0): " ++ show (squeeze i)
    
    let path = \dim -> if squeeze dim == I0 then "Start" else "End"
    putStrLn $ "Path at I0: " ++ path I0
    putStrLn $ "Path at I1: " ++ path I1
    putStrLn $ "Reversed Path at I0: " ++ rev path I0
    
    putStrLn "\nTesting Square Boundaries:"
    boundaryCheck mySquare
    